/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.fintech.Code', null, global);
goog.exportSymbol('proto.fintech.GetBalanceRequest', null, global);
goog.exportSymbol('proto.fintech.GetBalanceResponse', null, global);
goog.exportSymbol('proto.fintech.GetBalanceResponse.Data', null, global);
goog.exportSymbol('proto.fintech.GetHistoryRequest', null, global);
goog.exportSymbol('proto.fintech.GetHistoryResponse', null, global);
goog.exportSymbol('proto.fintech.GetHistoryResponse.Data', null, global);
goog.exportSymbol('proto.fintech.GetNotificationsRequest', null, global);
goog.exportSymbol('proto.fintech.GetNotificationsResponse', null, global);
goog.exportSymbol('proto.fintech.GetNotificationsResponse.Data', null, global);
goog.exportSymbol('proto.fintech.Notification', null, global);
goog.exportSymbol('proto.fintech.Notification.NotificationType', null, global);
goog.exportSymbol('proto.fintech.Status', null, global);
goog.exportSymbol('proto.fintech.TransactionHistory', null, global);
goog.exportSymbol('proto.fintech.TransactionHistory.TransferType', null, global);
goog.exportSymbol('proto.fintech.TransferMoneyRequest', null, global);
goog.exportSymbol('proto.fintech.TransferMoneyResponse', null, global);
goog.exportSymbol('proto.fintech.TransferMoneyResponse.Data', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.Status = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.Status, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.Status.displayName = 'proto.fintech.Status';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.Status.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.Status.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.Status} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.Status.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				code: jspb.Message.getFieldWithDefault(msg, 1, 0),
				message: jspb.Message.getFieldWithDefault(msg, 2, ''),
				extraMap: (f = msg.getExtraMap()) ? f.toObject(includeInstance, undefined) : []
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.Status}
 */
proto.fintech.Status.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.Status();
	return proto.fintech.Status.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.Status} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.Status}
 */
proto.fintech.Status.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value /** @type {!proto.fintech.Code} */ = reader.readEnum();
				msg.setCode(value);
				break;
			case 2:
				var value /** @type {string} */ = reader.readString();
				msg.setMessage(value);
				break;
			case 3:
				var value = msg.getExtraMap();
				reader.readMessage(value, function(message, reader) {
					jspb.Map.deserializeBinary(
						message,
						reader,
						jspb.BinaryReader.prototype.readString,
						jspb.BinaryReader.prototype.readString,
						null,
						''
					);
				});
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.Status.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.Status.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.Status} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.Status.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getCode();
	if (f !== 0.0) {
		writer.writeEnum(1, f);
	}
	f = message.getMessage();
	if (f.length > 0) {
		writer.writeString(2, f);
	}
	f = message.getExtraMap(true);
	if (f && f.getLength() > 0) {
		f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
	}
};

/**
 * optional Code code = 1;
 * @return {!proto.fintech.Code}
 */
proto.fintech.Status.prototype.getCode = function() {
	return /** @type {!proto.fintech.Code} */ jspb.Message.getFieldWithDefault(this, 1, 0);
};

/** @param {!proto.fintech.Code} value */
proto.fintech.Status.prototype.setCode = function(value) {
	jspb.Message.setProto3EnumField(this, 1, value);
};

/**
 * optional string message = 2;
 * @return {string}
 */
proto.fintech.Status.prototype.getMessage = function() {
	return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 2, '');
};

/** @param {string} value */
proto.fintech.Status.prototype.setMessage = function(value) {
	jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * map<string, string> extra = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.fintech.Status.prototype.getExtraMap = function(opt_noLazyCreate) {
	return /** @type {!jspb.Map<string,string>} */ jspb.Message.getMapField(this, 3, opt_noLazyCreate, null);
};

proto.fintech.Status.prototype.clearExtraMap = function() {
	this.getExtraMap().clear();
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.GetBalanceRequest = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.GetBalanceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.GetBalanceRequest.displayName = 'proto.fintech.GetBalanceRequest';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.GetBalanceRequest.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.GetBalanceRequest.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.GetBalanceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.GetBalanceRequest.toObject = function(includeInstance, msg) {
		var f,
			obj = {};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.GetBalanceRequest}
 */
proto.fintech.GetBalanceRequest.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.GetBalanceRequest();
	return proto.fintech.GetBalanceRequest.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.GetBalanceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.GetBalanceRequest}
 */
proto.fintech.GetBalanceRequest.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.GetBalanceRequest.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.GetBalanceRequest.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.GetBalanceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.GetBalanceRequest.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.GetBalanceResponse = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.GetBalanceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.GetBalanceResponse.displayName = 'proto.fintech.GetBalanceResponse';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.GetBalanceResponse.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.GetBalanceResponse.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.GetBalanceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.GetBalanceResponse.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				data: (f = msg.getData()) && proto.fintech.GetBalanceResponse.Data.toObject(includeInstance, f),
				status: (f = msg.getStatus()) && proto.fintech.Status.toObject(includeInstance, f)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.GetBalanceResponse}
 */
proto.fintech.GetBalanceResponse.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.GetBalanceResponse();
	return proto.fintech.GetBalanceResponse.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.GetBalanceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.GetBalanceResponse}
 */
proto.fintech.GetBalanceResponse.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = new proto.fintech.GetBalanceResponse.Data();
				reader.readMessage(value, proto.fintech.GetBalanceResponse.Data.deserializeBinaryFromReader);
				msg.setData(value);
				break;
			case 2:
				var value = new proto.fintech.Status();
				reader.readMessage(value, proto.fintech.Status.deserializeBinaryFromReader);
				msg.setStatus(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.GetBalanceResponse.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.GetBalanceResponse.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.GetBalanceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.GetBalanceResponse.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getData();
	if (f != null) {
		writer.writeMessage(1, f, proto.fintech.GetBalanceResponse.Data.serializeBinaryToWriter);
	}
	f = message.getStatus();
	if (f != null) {
		writer.writeMessage(2, f, proto.fintech.Status.serializeBinaryToWriter);
	}
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.GetBalanceResponse.Data = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.GetBalanceResponse.Data, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.GetBalanceResponse.Data.displayName = 'proto.fintech.GetBalanceResponse.Data';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.GetBalanceResponse.Data.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.GetBalanceResponse.Data.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.GetBalanceResponse.Data} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.GetBalanceResponse.Data.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				balance: jspb.Message.getFieldWithDefault(msg, 1, 0),
				lastUpdate: jspb.Message.getFieldWithDefault(msg, 2, 0)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.GetBalanceResponse.Data}
 */
proto.fintech.GetBalanceResponse.Data.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.GetBalanceResponse.Data();
	return proto.fintech.GetBalanceResponse.Data.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.GetBalanceResponse.Data} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.GetBalanceResponse.Data}
 */
proto.fintech.GetBalanceResponse.Data.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value /** @type {number} */ = reader.readInt64();
				msg.setBalance(value);
				break;
			case 2:
				var value /** @type {number} */ = reader.readInt64();
				msg.setLastUpdate(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.GetBalanceResponse.Data.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.GetBalanceResponse.Data.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.GetBalanceResponse.Data} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.GetBalanceResponse.Data.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getBalance();
	if (f !== 0) {
		writer.writeInt64(1, f);
	}
	f = message.getLastUpdate();
	if (f !== 0) {
		writer.writeInt64(2, f);
	}
};

/**
 * optional int64 balance = 1;
 * @return {number}
 */
proto.fintech.GetBalanceResponse.Data.prototype.getBalance = function() {
	return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 1, 0);
};

/** @param {number} value */
proto.fintech.GetBalanceResponse.Data.prototype.setBalance = function(value) {
	jspb.Message.setProto3IntField(this, 1, value);
};

/**
 * optional int64 last_update = 2;
 * @return {number}
 */
proto.fintech.GetBalanceResponse.Data.prototype.getLastUpdate = function() {
	return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 2, 0);
};

/** @param {number} value */
proto.fintech.GetBalanceResponse.Data.prototype.setLastUpdate = function(value) {
	jspb.Message.setProto3IntField(this, 2, value);
};

/**
 * optional Data data = 1;
 * @return {?proto.fintech.GetBalanceResponse.Data}
 */
proto.fintech.GetBalanceResponse.prototype.getData = function() {
	return /** @type{?proto.fintech.GetBalanceResponse.Data} */ jspb.Message.getWrapperField(
		this,
		proto.fintech.GetBalanceResponse.Data,
		1
	);
};

/** @param {?proto.fintech.GetBalanceResponse.Data|undefined} value */
proto.fintech.GetBalanceResponse.prototype.setData = function(value) {
	jspb.Message.setWrapperField(this, 1, value);
};

proto.fintech.GetBalanceResponse.prototype.clearData = function() {
	this.setData(undefined);
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fintech.GetBalanceResponse.prototype.hasData = function() {
	return jspb.Message.getField(this, 1) != null;
};

/**
 * optional Status status = 2;
 * @return {?proto.fintech.Status}
 */
proto.fintech.GetBalanceResponse.prototype.getStatus = function() {
	return /** @type{?proto.fintech.Status} */ jspb.Message.getWrapperField(this, proto.fintech.Status, 2);
};

/** @param {?proto.fintech.Status|undefined} value */
proto.fintech.GetBalanceResponse.prototype.setStatus = function(value) {
	jspb.Message.setWrapperField(this, 2, value);
};

proto.fintech.GetBalanceResponse.prototype.clearStatus = function() {
	this.setStatus(undefined);
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fintech.GetBalanceResponse.prototype.hasStatus = function() {
	return jspb.Message.getField(this, 2) != null;
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.TransferMoneyRequest = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.TransferMoneyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.TransferMoneyRequest.displayName = 'proto.fintech.TransferMoneyRequest';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.TransferMoneyRequest.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.TransferMoneyRequest.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.TransferMoneyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.TransferMoneyRequest.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				receiver: jspb.Message.getFieldWithDefault(msg, 2, ''),
				amount: jspb.Message.getFieldWithDefault(msg, 3, 0),
				description: jspb.Message.getFieldWithDefault(msg, 4, '')
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.TransferMoneyRequest}
 */
proto.fintech.TransferMoneyRequest.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.TransferMoneyRequest();
	return proto.fintech.TransferMoneyRequest.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.TransferMoneyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.TransferMoneyRequest}
 */
proto.fintech.TransferMoneyRequest.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 2:
				var value /** @type {string} */ = reader.readString();
				msg.setReceiver(value);
				break;
			case 3:
				var value /** @type {number} */ = reader.readInt64();
				msg.setAmount(value);
				break;
			case 4:
				var value /** @type {string} */ = reader.readString();
				msg.setDescription(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.TransferMoneyRequest.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.TransferMoneyRequest.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.TransferMoneyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.TransferMoneyRequest.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getReceiver();
	if (f.length > 0) {
		writer.writeString(2, f);
	}
	f = message.getAmount();
	if (f !== 0) {
		writer.writeInt64(3, f);
	}
	f = message.getDescription();
	if (f.length > 0) {
		writer.writeString(4, f);
	}
};

/**
 * optional string receiver = 2;
 * @return {string}
 */
proto.fintech.TransferMoneyRequest.prototype.getReceiver = function() {
	return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 2, '');
};

/** @param {string} value */
proto.fintech.TransferMoneyRequest.prototype.setReceiver = function(value) {
	jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional int64 amount = 3;
 * @return {number}
 */
proto.fintech.TransferMoneyRequest.prototype.getAmount = function() {
	return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 3, 0);
};

/** @param {number} value */
proto.fintech.TransferMoneyRequest.prototype.setAmount = function(value) {
	jspb.Message.setProto3IntField(this, 3, value);
};

/**
 * optional string description = 4;
 * @return {string}
 */
proto.fintech.TransferMoneyRequest.prototype.getDescription = function() {
	return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 4, '');
};

/** @param {string} value */
proto.fintech.TransferMoneyRequest.prototype.setDescription = function(value) {
	jspb.Message.setProto3StringField(this, 4, value);
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.TransferMoneyResponse = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.TransferMoneyResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.TransferMoneyResponse.displayName = 'proto.fintech.TransferMoneyResponse';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.TransferMoneyResponse.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.TransferMoneyResponse.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.TransferMoneyResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.TransferMoneyResponse.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				data: (f = msg.getData()) && proto.fintech.TransferMoneyResponse.Data.toObject(includeInstance, f),
				status: (f = msg.getStatus()) && proto.fintech.Status.toObject(includeInstance, f)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.TransferMoneyResponse}
 */
proto.fintech.TransferMoneyResponse.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.TransferMoneyResponse();
	return proto.fintech.TransferMoneyResponse.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.TransferMoneyResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.TransferMoneyResponse}
 */
proto.fintech.TransferMoneyResponse.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = new proto.fintech.TransferMoneyResponse.Data();
				reader.readMessage(value, proto.fintech.TransferMoneyResponse.Data.deserializeBinaryFromReader);
				msg.setData(value);
				break;
			case 2:
				var value = new proto.fintech.Status();
				reader.readMessage(value, proto.fintech.Status.deserializeBinaryFromReader);
				msg.setStatus(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.TransferMoneyResponse.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.TransferMoneyResponse.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.TransferMoneyResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.TransferMoneyResponse.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getData();
	if (f != null) {
		writer.writeMessage(1, f, proto.fintech.TransferMoneyResponse.Data.serializeBinaryToWriter);
	}
	f = message.getStatus();
	if (f != null) {
		writer.writeMessage(2, f, proto.fintech.Status.serializeBinaryToWriter);
	}
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.TransferMoneyResponse.Data = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.TransferMoneyResponse.Data, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.TransferMoneyResponse.Data.displayName = 'proto.fintech.TransferMoneyResponse.Data';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.TransferMoneyResponse.Data.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.TransferMoneyResponse.Data.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.TransferMoneyResponse.Data} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.TransferMoneyResponse.Data.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				balance: jspb.Message.getFieldWithDefault(msg, 1, 0)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.TransferMoneyResponse.Data}
 */
proto.fintech.TransferMoneyResponse.Data.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.TransferMoneyResponse.Data();
	return proto.fintech.TransferMoneyResponse.Data.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.TransferMoneyResponse.Data} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.TransferMoneyResponse.Data}
 */
proto.fintech.TransferMoneyResponse.Data.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value /** @type {number} */ = reader.readInt64();
				msg.setBalance(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.TransferMoneyResponse.Data.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.TransferMoneyResponse.Data.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.TransferMoneyResponse.Data} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.TransferMoneyResponse.Data.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getBalance();
	if (f !== 0) {
		writer.writeInt64(1, f);
	}
};

/**
 * optional int64 balance = 1;
 * @return {number}
 */
proto.fintech.TransferMoneyResponse.Data.prototype.getBalance = function() {
	return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 1, 0);
};

/** @param {number} value */
proto.fintech.TransferMoneyResponse.Data.prototype.setBalance = function(value) {
	jspb.Message.setProto3IntField(this, 1, value);
};

/**
 * optional Data data = 1;
 * @return {?proto.fintech.TransferMoneyResponse.Data}
 */
proto.fintech.TransferMoneyResponse.prototype.getData = function() {
	return /** @type{?proto.fintech.TransferMoneyResponse.Data} */ jspb.Message.getWrapperField(
		this,
		proto.fintech.TransferMoneyResponse.Data,
		1
	);
};

/** @param {?proto.fintech.TransferMoneyResponse.Data|undefined} value */
proto.fintech.TransferMoneyResponse.prototype.setData = function(value) {
	jspb.Message.setWrapperField(this, 1, value);
};

proto.fintech.TransferMoneyResponse.prototype.clearData = function() {
	this.setData(undefined);
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fintech.TransferMoneyResponse.prototype.hasData = function() {
	return jspb.Message.getField(this, 1) != null;
};

/**
 * optional Status status = 2;
 * @return {?proto.fintech.Status}
 */
proto.fintech.TransferMoneyResponse.prototype.getStatus = function() {
	return /** @type{?proto.fintech.Status} */ jspb.Message.getWrapperField(this, proto.fintech.Status, 2);
};

/** @param {?proto.fintech.Status|undefined} value */
proto.fintech.TransferMoneyResponse.prototype.setStatus = function(value) {
	jspb.Message.setWrapperField(this, 2, value);
};

proto.fintech.TransferMoneyResponse.prototype.clearStatus = function() {
	this.setStatus(undefined);
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fintech.TransferMoneyResponse.prototype.hasStatus = function() {
	return jspb.Message.getField(this, 2) != null;
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.GetHistoryRequest = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.GetHistoryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.GetHistoryRequest.displayName = 'proto.fintech.GetHistoryRequest';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.GetHistoryRequest.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.GetHistoryRequest.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.GetHistoryRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.GetHistoryRequest.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				pageSize: jspb.Message.getFieldWithDefault(msg, 2, 0),
				pageToken: jspb.Message.getFieldWithDefault(msg, 3, 0)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.GetHistoryRequest}
 */
proto.fintech.GetHistoryRequest.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.GetHistoryRequest();
	return proto.fintech.GetHistoryRequest.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.GetHistoryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.GetHistoryRequest}
 */
proto.fintech.GetHistoryRequest.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 2:
				var value /** @type {number} */ = reader.readInt32();
				msg.setPageSize(value);
				break;
			case 3:
				var value /** @type {number} */ = reader.readInt32();
				msg.setPageToken(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.GetHistoryRequest.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.GetHistoryRequest.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.GetHistoryRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.GetHistoryRequest.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getPageSize();
	if (f !== 0) {
		writer.writeInt32(2, f);
	}
	f = message.getPageToken();
	if (f !== 0) {
		writer.writeInt32(3, f);
	}
};

/**
 * optional int32 page_size = 2;
 * @return {number}
 */
proto.fintech.GetHistoryRequest.prototype.getPageSize = function() {
	return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 2, 0);
};

/** @param {number} value */
proto.fintech.GetHistoryRequest.prototype.setPageSize = function(value) {
	jspb.Message.setProto3IntField(this, 2, value);
};

/**
 * optional int32 page_token = 3;
 * @return {number}
 */
proto.fintech.GetHistoryRequest.prototype.getPageToken = function() {
	return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 3, 0);
};

/** @param {number} value */
proto.fintech.GetHistoryRequest.prototype.setPageToken = function(value) {
	jspb.Message.setProto3IntField(this, 3, value);
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.TransactionHistory = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.TransactionHistory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.TransactionHistory.displayName = 'proto.fintech.TransactionHistory';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.TransactionHistory.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.TransactionHistory.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.TransactionHistory} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.TransactionHistory.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				userId: jspb.Message.getFieldWithDefault(msg, 1, ''),
				amount: jspb.Message.getFieldWithDefault(msg, 2, 0),
				description: jspb.Message.getFieldWithDefault(msg, 3, ''),
				recordedTime: jspb.Message.getFieldWithDefault(msg, 4, ''),
				transferType: jspb.Message.getFieldWithDefault(msg, 5, 0)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.TransactionHistory}
 */
proto.fintech.TransactionHistory.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.TransactionHistory();
	return proto.fintech.TransactionHistory.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.TransactionHistory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.TransactionHistory}
 */
proto.fintech.TransactionHistory.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value /** @type {string} */ = reader.readString();
				msg.setUserId(value);
				break;
			case 2:
				var value /** @type {number} */ = reader.readInt64();
				msg.setAmount(value);
				break;
			case 3:
				var value /** @type {string} */ = reader.readString();
				msg.setDescription(value);
				break;
			case 4:
				var value /** @type {string} */ = reader.readString();
				msg.setRecordedTime(value);
				break;
			case 5:
				var value /** @type {!proto.fintech.TransactionHistory.TransferType} */ = reader.readEnum();
				msg.setTransferType(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.TransactionHistory.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.TransactionHistory.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.TransactionHistory} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.TransactionHistory.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getUserId();
	if (f.length > 0) {
		writer.writeString(1, f);
	}
	f = message.getAmount();
	if (f !== 0) {
		writer.writeInt64(2, f);
	}
	f = message.getDescription();
	if (f.length > 0) {
		writer.writeString(3, f);
	}
	f = message.getRecordedTime();
	if (f.length > 0) {
		writer.writeString(4, f);
	}
	f = message.getTransferType();
	if (f !== 0.0) {
		writer.writeEnum(5, f);
	}
};

/**
 * @enum {number}
 */
proto.fintech.TransactionHistory.TransferType = {
	SEND: 0,
	RECEIVE: 1
};

/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.fintech.TransactionHistory.prototype.getUserId = function() {
	return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 1, '');
};

/** @param {string} value */
proto.fintech.TransactionHistory.prototype.setUserId = function(value) {
	jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional int64 amount = 2;
 * @return {number}
 */
proto.fintech.TransactionHistory.prototype.getAmount = function() {
	return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 2, 0);
};

/** @param {number} value */
proto.fintech.TransactionHistory.prototype.setAmount = function(value) {
	jspb.Message.setProto3IntField(this, 2, value);
};

/**
 * optional string description = 3;
 * @return {string}
 */
proto.fintech.TransactionHistory.prototype.getDescription = function() {
	return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 3, '');
};

/** @param {string} value */
proto.fintech.TransactionHistory.prototype.setDescription = function(value) {
	jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional string recorded_time = 4;
 * @return {string}
 */
proto.fintech.TransactionHistory.prototype.getRecordedTime = function() {
	return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 4, '');
};

/** @param {string} value */
proto.fintech.TransactionHistory.prototype.setRecordedTime = function(value) {
	jspb.Message.setProto3StringField(this, 4, value);
};

/**
 * optional TransferType transfer_type = 5;
 * @return {!proto.fintech.TransactionHistory.TransferType}
 */
proto.fintech.TransactionHistory.prototype.getTransferType = function() {
	return /** @type {!proto.fintech.TransactionHistory.TransferType} */ jspb.Message.getFieldWithDefault(this, 5, 0);
};

/** @param {!proto.fintech.TransactionHistory.TransferType} value */
proto.fintech.TransactionHistory.prototype.setTransferType = function(value) {
	jspb.Message.setProto3EnumField(this, 5, value);
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.GetHistoryResponse = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.GetHistoryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.GetHistoryResponse.displayName = 'proto.fintech.GetHistoryResponse';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.GetHistoryResponse.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.GetHistoryResponse.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.GetHistoryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.GetHistoryResponse.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				data: (f = msg.getData()) && proto.fintech.GetHistoryResponse.Data.toObject(includeInstance, f),
				status: (f = msg.getStatus()) && proto.fintech.Status.toObject(includeInstance, f)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.GetHistoryResponse}
 */
proto.fintech.GetHistoryResponse.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.GetHistoryResponse();
	return proto.fintech.GetHistoryResponse.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.GetHistoryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.GetHistoryResponse}
 */
proto.fintech.GetHistoryResponse.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = new proto.fintech.GetHistoryResponse.Data();
				reader.readMessage(value, proto.fintech.GetHistoryResponse.Data.deserializeBinaryFromReader);
				msg.setData(value);
				break;
			case 2:
				var value = new proto.fintech.Status();
				reader.readMessage(value, proto.fintech.Status.deserializeBinaryFromReader);
				msg.setStatus(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.GetHistoryResponse.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.GetHistoryResponse.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.GetHistoryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.GetHistoryResponse.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getData();
	if (f != null) {
		writer.writeMessage(1, f, proto.fintech.GetHistoryResponse.Data.serializeBinaryToWriter);
	}
	f = message.getStatus();
	if (f != null) {
		writer.writeMessage(2, f, proto.fintech.Status.serializeBinaryToWriter);
	}
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.GetHistoryResponse.Data = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, proto.fintech.GetHistoryResponse.Data.repeatedFields_, null);
};
goog.inherits(proto.fintech.GetHistoryResponse.Data, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.GetHistoryResponse.Data.displayName = 'proto.fintech.GetHistoryResponse.Data';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fintech.GetHistoryResponse.Data.repeatedFields_ = [ 1 ];

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.GetHistoryResponse.Data.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.GetHistoryResponse.Data.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.GetHistoryResponse.Data} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.GetHistoryResponse.Data.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				historiesList: jspb.Message.toObjectList(
					msg.getHistoriesList(),
					proto.fintech.TransactionHistory.toObject,
					includeInstance
				),
				nextPageToken: jspb.Message.getFieldWithDefault(msg, 2, 0)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.GetHistoryResponse.Data}
 */
proto.fintech.GetHistoryResponse.Data.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.GetHistoryResponse.Data();
	return proto.fintech.GetHistoryResponse.Data.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.GetHistoryResponse.Data} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.GetHistoryResponse.Data}
 */
proto.fintech.GetHistoryResponse.Data.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = new proto.fintech.TransactionHistory();
				reader.readMessage(value, proto.fintech.TransactionHistory.deserializeBinaryFromReader);
				msg.addHistories(value);
				break;
			case 2:
				var value /** @type {number} */ = reader.readInt32();
				msg.setNextPageToken(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.GetHistoryResponse.Data.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.GetHistoryResponse.Data.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.GetHistoryResponse.Data} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.GetHistoryResponse.Data.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getHistoriesList();
	if (f.length > 0) {
		writer.writeRepeatedMessage(1, f, proto.fintech.TransactionHistory.serializeBinaryToWriter);
	}
	f = message.getNextPageToken();
	if (f !== 0) {
		writer.writeInt32(2, f);
	}
};

/**
 * repeated TransactionHistory histories = 1;
 * @return {!Array<!proto.fintech.TransactionHistory>}
 */
proto.fintech.GetHistoryResponse.Data.prototype.getHistoriesList = function() {
	return /** @type{!Array<!proto.fintech.TransactionHistory>} */ jspb.Message.getRepeatedWrapperField(
		this,
		proto.fintech.TransactionHistory,
		1
	);
};

/** @param {!Array<!proto.fintech.TransactionHistory>} value */
proto.fintech.GetHistoryResponse.Data.prototype.setHistoriesList = function(value) {
	jspb.Message.setRepeatedWrapperField(this, 1, value);
};

/**
 * @param {!proto.fintech.TransactionHistory=} opt_value
 * @param {number=} opt_index
 * @return {!proto.fintech.TransactionHistory}
 */
proto.fintech.GetHistoryResponse.Data.prototype.addHistories = function(opt_value, opt_index) {
	return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.fintech.TransactionHistory, opt_index);
};

proto.fintech.GetHistoryResponse.Data.prototype.clearHistoriesList = function() {
	this.setHistoriesList([]);
};

/**
 * optional int32 next_page_token = 2;
 * @return {number}
 */
proto.fintech.GetHistoryResponse.Data.prototype.getNextPageToken = function() {
	return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 2, 0);
};

/** @param {number} value */
proto.fintech.GetHistoryResponse.Data.prototype.setNextPageToken = function(value) {
	jspb.Message.setProto3IntField(this, 2, value);
};

/**
 * optional Data data = 1;
 * @return {?proto.fintech.GetHistoryResponse.Data}
 */
proto.fintech.GetHistoryResponse.prototype.getData = function() {
	return /** @type{?proto.fintech.GetHistoryResponse.Data} */ jspb.Message.getWrapperField(
		this,
		proto.fintech.GetHistoryResponse.Data,
		1
	);
};

/** @param {?proto.fintech.GetHistoryResponse.Data|undefined} value */
proto.fintech.GetHistoryResponse.prototype.setData = function(value) {
	jspb.Message.setWrapperField(this, 1, value);
};

proto.fintech.GetHistoryResponse.prototype.clearData = function() {
	this.setData(undefined);
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fintech.GetHistoryResponse.prototype.hasData = function() {
	return jspb.Message.getField(this, 1) != null;
};

/**
 * optional Status status = 2;
 * @return {?proto.fintech.Status}
 */
proto.fintech.GetHistoryResponse.prototype.getStatus = function() {
	return /** @type{?proto.fintech.Status} */ jspb.Message.getWrapperField(this, proto.fintech.Status, 2);
};

/** @param {?proto.fintech.Status|undefined} value */
proto.fintech.GetHistoryResponse.prototype.setStatus = function(value) {
	jspb.Message.setWrapperField(this, 2, value);
};

proto.fintech.GetHistoryResponse.prototype.clearStatus = function() {
	this.setStatus(undefined);
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fintech.GetHistoryResponse.prototype.hasStatus = function() {
	return jspb.Message.getField(this, 2) != null;
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.GetNotificationsRequest = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.GetNotificationsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.GetNotificationsRequest.displayName = 'proto.fintech.GetNotificationsRequest';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.GetNotificationsRequest.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.GetNotificationsRequest.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.GetNotificationsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.GetNotificationsRequest.toObject = function(includeInstance, msg) {
		var f,
			obj = {};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.GetNotificationsRequest}
 */
proto.fintech.GetNotificationsRequest.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.GetNotificationsRequest();
	return proto.fintech.GetNotificationsRequest.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.GetNotificationsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.GetNotificationsRequest}
 */
proto.fintech.GetNotificationsRequest.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.GetNotificationsRequest.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.GetNotificationsRequest.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.GetNotificationsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.GetNotificationsRequest.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.Notification = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.Notification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.Notification.displayName = 'proto.fintech.Notification';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.Notification.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.Notification.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.Notification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.Notification.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				userId: jspb.Message.getFieldWithDefault(msg, 1, ''),
				amount: jspb.Message.getFieldWithDefault(msg, 2, 0),
				message: jspb.Message.getFieldWithDefault(msg, 3, ''),
				recordedTime: jspb.Message.getFieldWithDefault(msg, 4, ''),
				notificationType: jspb.Message.getFieldWithDefault(msg, 5, 0)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.Notification}
 */
proto.fintech.Notification.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.Notification();
	return proto.fintech.Notification.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.Notification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.Notification}
 */
proto.fintech.Notification.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value /** @type {string} */ = reader.readString();
				msg.setUserId(value);
				break;
			case 2:
				var value /** @type {number} */ = reader.readInt64();
				msg.setAmount(value);
				break;
			case 3:
				var value /** @type {string} */ = reader.readString();
				msg.setMessage(value);
				break;
			case 4:
				var value /** @type {string} */ = reader.readString();
				msg.setRecordedTime(value);
				break;
			case 5:
				var value /** @type {!proto.fintech.Notification.NotificationType} */ = reader.readEnum();
				msg.setNotificationType(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.Notification.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.Notification.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.Notification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.Notification.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getUserId();
	if (f.length > 0) {
		writer.writeString(1, f);
	}
	f = message.getAmount();
	if (f !== 0) {
		writer.writeInt64(2, f);
	}
	f = message.getMessage();
	if (f.length > 0) {
		writer.writeString(3, f);
	}
	f = message.getRecordedTime();
	if (f.length > 0) {
		writer.writeString(4, f);
	}
	f = message.getNotificationType();
	if (f !== 0.0) {
		writer.writeEnum(5, f);
	}
};

/**
 * @enum {number}
 */
proto.fintech.Notification.NotificationType = {
	REMINDED: 0,
	RECEIVED: 1
};

/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.fintech.Notification.prototype.getUserId = function() {
	return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 1, '');
};

/** @param {string} value */
proto.fintech.Notification.prototype.setUserId = function(value) {
	jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional int64 amount = 2;
 * @return {number}
 */
proto.fintech.Notification.prototype.getAmount = function() {
	return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 2, 0);
};

/** @param {number} value */
proto.fintech.Notification.prototype.setAmount = function(value) {
	jspb.Message.setProto3IntField(this, 2, value);
};

/**
 * optional string message = 3;
 * @return {string}
 */
proto.fintech.Notification.prototype.getMessage = function() {
	return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 3, '');
};

/** @param {string} value */
proto.fintech.Notification.prototype.setMessage = function(value) {
	jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional string recorded_time = 4;
 * @return {string}
 */
proto.fintech.Notification.prototype.getRecordedTime = function() {
	return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 4, '');
};

/** @param {string} value */
proto.fintech.Notification.prototype.setRecordedTime = function(value) {
	jspb.Message.setProto3StringField(this, 4, value);
};

/**
 * optional NotificationType notification_type = 5;
 * @return {!proto.fintech.Notification.NotificationType}
 */
proto.fintech.Notification.prototype.getNotificationType = function() {
	return /** @type {!proto.fintech.Notification.NotificationType} */ jspb.Message.getFieldWithDefault(this, 5, 0);
};

/** @param {!proto.fintech.Notification.NotificationType} value */
proto.fintech.Notification.prototype.setNotificationType = function(value) {
	jspb.Message.setProto3EnumField(this, 5, value);
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.GetNotificationsResponse = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fintech.GetNotificationsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.GetNotificationsResponse.displayName = 'proto.fintech.GetNotificationsResponse';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.GetNotificationsResponse.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.GetNotificationsResponse.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.GetNotificationsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.GetNotificationsResponse.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				data: (f = msg.getData()) && proto.fintech.GetNotificationsResponse.Data.toObject(includeInstance, f),
				status: (f = msg.getStatus()) && proto.fintech.Status.toObject(includeInstance, f)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.GetNotificationsResponse}
 */
proto.fintech.GetNotificationsResponse.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.GetNotificationsResponse();
	return proto.fintech.GetNotificationsResponse.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.GetNotificationsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.GetNotificationsResponse}
 */
proto.fintech.GetNotificationsResponse.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = new proto.fintech.GetNotificationsResponse.Data();
				reader.readMessage(value, proto.fintech.GetNotificationsResponse.Data.deserializeBinaryFromReader);
				msg.setData(value);
				break;
			case 2:
				var value = new proto.fintech.Status();
				reader.readMessage(value, proto.fintech.Status.deserializeBinaryFromReader);
				msg.setStatus(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.GetNotificationsResponse.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.GetNotificationsResponse.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.GetNotificationsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.GetNotificationsResponse.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getData();
	if (f != null) {
		writer.writeMessage(1, f, proto.fintech.GetNotificationsResponse.Data.serializeBinaryToWriter);
	}
	f = message.getStatus();
	if (f != null) {
		writer.writeMessage(2, f, proto.fintech.Status.serializeBinaryToWriter);
	}
};

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fintech.GetNotificationsResponse.Data = function(opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, proto.fintech.GetNotificationsResponse.Data.repeatedFields_, null);
};
goog.inherits(proto.fintech.GetNotificationsResponse.Data, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	proto.fintech.GetNotificationsResponse.Data.displayName = 'proto.fintech.GetNotificationsResponse.Data';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fintech.GetNotificationsResponse.Data.repeatedFields_ = [ 1 ];

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
	proto.fintech.GetNotificationsResponse.Data.prototype.toObject = function(opt_includeInstance) {
		return proto.fintech.GetNotificationsResponse.Data.toObject(opt_includeInstance, this);
	};

	/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fintech.GetNotificationsResponse.Data} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
	proto.fintech.GetNotificationsResponse.Data.toObject = function(includeInstance, msg) {
		var f,
			obj = {
				notificationList: jspb.Message.toObjectList(
					msg.getNotificationList(),
					proto.fintech.Notification.toObject,
					includeInstance
				),
				nextPageToken: jspb.Message.getFieldWithDefault(msg, 2, 0)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fintech.GetNotificationsResponse.Data}
 */
proto.fintech.GetNotificationsResponse.Data.deserializeBinary = function(bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.fintech.GetNotificationsResponse.Data();
	return proto.fintech.GetNotificationsResponse.Data.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fintech.GetNotificationsResponse.Data} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fintech.GetNotificationsResponse.Data}
 */
proto.fintech.GetNotificationsResponse.Data.deserializeBinaryFromReader = function(msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = new proto.fintech.Notification();
				reader.readMessage(value, proto.fintech.Notification.deserializeBinaryFromReader);
				msg.addNotification(value);
				break;
			case 2:
				var value /** @type {number} */ = reader.readInt32();
				msg.setNextPageToken(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fintech.GetNotificationsResponse.Data.prototype.serializeBinary = function() {
	var writer = new jspb.BinaryWriter();
	proto.fintech.GetNotificationsResponse.Data.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fintech.GetNotificationsResponse.Data} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fintech.GetNotificationsResponse.Data.serializeBinaryToWriter = function(message, writer) {
	var f = undefined;
	f = message.getNotificationList();
	if (f.length > 0) {
		writer.writeRepeatedMessage(1, f, proto.fintech.Notification.serializeBinaryToWriter);
	}
	f = message.getNextPageToken();
	if (f !== 0) {
		writer.writeInt32(2, f);
	}
};

/**
 * repeated Notification notification = 1;
 * @return {!Array<!proto.fintech.Notification>}
 */
proto.fintech.GetNotificationsResponse.Data.prototype.getNotificationList = function() {
	return /** @type{!Array<!proto.fintech.Notification>} */ jspb.Message.getRepeatedWrapperField(
		this,
		proto.fintech.Notification,
		1
	);
};

/** @param {!Array<!proto.fintech.Notification>} value */
proto.fintech.GetNotificationsResponse.Data.prototype.setNotificationList = function(value) {
	jspb.Message.setRepeatedWrapperField(this, 1, value);
};

/**
 * @param {!proto.fintech.Notification=} opt_value
 * @param {number=} opt_index
 * @return {!proto.fintech.Notification}
 */
proto.fintech.GetNotificationsResponse.Data.prototype.addNotification = function(opt_value, opt_index) {
	return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.fintech.Notification, opt_index);
};

proto.fintech.GetNotificationsResponse.Data.prototype.clearNotificationList = function() {
	this.setNotificationList([]);
};

/**
 * optional int32 next_page_token = 2;
 * @return {number}
 */
proto.fintech.GetNotificationsResponse.Data.prototype.getNextPageToken = function() {
	return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 2, 0);
};

/** @param {number} value */
proto.fintech.GetNotificationsResponse.Data.prototype.setNextPageToken = function(value) {
	jspb.Message.setProto3IntField(this, 2, value);
};

/**
 * optional Data data = 1;
 * @return {?proto.fintech.GetNotificationsResponse.Data}
 */
proto.fintech.GetNotificationsResponse.prototype.getData = function() {
	return /** @type{?proto.fintech.GetNotificationsResponse.Data} */ jspb.Message.getWrapperField(
		this,
		proto.fintech.GetNotificationsResponse.Data,
		1
	);
};

/** @param {?proto.fintech.GetNotificationsResponse.Data|undefined} value */
proto.fintech.GetNotificationsResponse.prototype.setData = function(value) {
	jspb.Message.setWrapperField(this, 1, value);
};

proto.fintech.GetNotificationsResponse.prototype.clearData = function() {
	this.setData(undefined);
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fintech.GetNotificationsResponse.prototype.hasData = function() {
	return jspb.Message.getField(this, 1) != null;
};

/**
 * optional Status status = 2;
 * @return {?proto.fintech.Status}
 */
proto.fintech.GetNotificationsResponse.prototype.getStatus = function() {
	return /** @type{?proto.fintech.Status} */ jspb.Message.getWrapperField(this, proto.fintech.Status, 2);
};

/** @param {?proto.fintech.Status|undefined} value */
proto.fintech.GetNotificationsResponse.prototype.setStatus = function(value) {
	jspb.Message.setWrapperField(this, 2, value);
};

proto.fintech.GetNotificationsResponse.prototype.clearStatus = function() {
	this.setStatus(undefined);
};

/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.fintech.GetNotificationsResponse.prototype.hasStatus = function() {
	return jspb.Message.getField(this, 2) != null;
};

/**
 * @enum {number}
 */
proto.fintech.Code = {
	OK: 0,
	NOT_ENOUGH_MONEY: 1,
	INVALID_PASSWORD: 2,
	FAILED_PRECONDITION: 3,
	INTERNAL: 4,
	INVALID_INPUT_MONEY: 5
};

goog.object.extend(exports, proto.fintech);
