{
 "title": "Foo-app",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Select latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "DB_seconds_count{step=\"query-ok\"}"
    }
   ]
  },
  {
   "title": "Insert, Update latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "DB_seconds_count{step=\"execute-ok\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "targets": [
    { "expr": "system_cpu_usage*100" }
   ]
  },
  {
   "title": "Online users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "vertx_http_server_wsConnections"
    }
   ]
  },
  {
   "title": "GRpc Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(TransferMoneyHandler_seconds_bucket[5m])) by (le))",
     "legendFormat": "transfer_money [99p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(GetBalanceHandler_seconds_bucket[5m])) by (le))",
     "legendFormat": "get_balance [99p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(GetHistoryHandler_seconds_bucket[5m])) by (le))",
     "legendFormat": "get_history_handler [99p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(AddFriendHandler_seconds_bucket[5m])) by (le))",
     "legendFormat": "add_friend_handler [99p]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(GetFriendListHandler_seconds_bucket[5m])) by (le))",
     "legendFormat": "get_friend_list [99p]"
    }
   ]
  },
  {
   "title": "DB operate response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(DB_seconds_bucket[5m])) by (le,step))"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vertx_http_server_connections", "legendFormat": "{{local}}" }
   ]
  },
  {
   "title": "Request count rate by error code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requestCount_total[1m])) by (code), 0.001)"
    }
   ]
  },
  {
   "title": "Request count rate by code and path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(vertx_http_server_requestCount_total[1m])) by (local,code,path), 0.001)"
    }
   ]
  },
  {
   "title": "Global response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum[1m])) / sum(irate(vertx_http_server_responseTime_seconds_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Response time by path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum[1m])) by (path) / sum(irate(vertx_http_server_responseTime_seconds_count[1m])) by (path)",
     "legendFormat": "{{path}} [avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le,path))",
     "legendFormat": "{{path}} [med]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_responseTime_seconds_bucket[1m])) by (le,path))",
     "legendFormat": "{{path}} [99p]"
    }
   ]
  },
  {
   "title": "HTTP Server bytes sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesSent_sum[1m])) / sum(rate(vertx_http_server_bytesSent_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_bytesSent_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_bytesSent_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_bytesSent_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "HTTP Server bytes received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vertx_http_server_bytesReceived_sum[1m])) / sum(rate(vertx_http_server_bytesReceived_count[1m]))",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(vertx_http_server_bytesReceived_bucket[1m])) by (le))",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vertx_http_server_bytesReceived_bucket[1m])) by (le))",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(vertx_http_server_bytesReceived_bucket[1m])) by (le))",
     "legendFormat": "[99p]"
    }
   ]
  }
 ]
}