@startuml removeafriend
hide footbox

actor "User A"

"User A" -> "App Server": Sent a POST request (with JWT + username) \nto remove a friend
"App Server" -> "Redis Server": Check JWT BlackList
"App Server" -> "MySql Server": Validate JWT then remove in friend list
"App Server" -> "User A": Return result to user A

@enduml