version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  database:
    image: "mysql:8.0.21"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./foo-run/foo-database/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql:ro
  cache:
    image: "redis"
    ports:
      - "6379:6379"
  envoy:
    container_name: envoy-proxy
    image: envoyproxy/envoy:v1.15.0
    ports:
      - 8080:8080
      - 9901:9901
    volumes:
      - ./foo-frontend/envoy.yaml:/etc/envoy/envoy.yaml:ro
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./foo-run/foo-monitoring/:/etc/prometheus/
      # - prometheus_data:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    network_mode: host

  grafana:
    image: grafana/grafana:6.3.5
    ports:
      - 3000:3000
    # command:
    # - -e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secrect
    volumes:
      - grafana_data:/var/lib/grafana
    network_mode: host
  # backend:
  #   depends_on:
  #     - database
  #     - cache
  #   build:
  #     context: .
  #     dockerfile: ./foo-run/foo-backend/Dockerfile
  #   network_mode: host
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./foo-run/foo-frontend/Dockerfile
  #   network_mode: host
