@startuml chatsingle
hide footbox
actor "User A"
actor "User B"
"User A" -> "Server": send {message, receiverId}
"Server" -> "MySQL": store this message to database
"MySQL" --> "Server": save message to db done
"Server" -> "Redis": add to most recent \nchat message cache.
"Redis" --> "Server": save message to cache done
"Server" --> "User B": send message to receiver
"Server" --> "User A": send message to sender
@enduml