@startuml login
hide footbox
actor "User A"
"User A" -> "Server": newTransfer(B, amount)
"Server" -> "MySQL": do transaction transfer money A to B

"Server" -> "MySQL": get balance of A
"MySQL" -> "Server": A's balance
"Server" -> "Server" : check amount <= balance
alt (amount > balance)
"Server" -> "User A": NOT_ENOUGH_MONEY
else (amount <= balance)
"Server" -> "MySQL" : (-) A's balance and (+) B's balance
end
alt (do not exist)
"MySQL" --> "Server": do not find user with username
"Server" --> "User": user do not exist
else (username exist)
"MySQL" --> "Server": get user with username
"Server" -> "Server": validate password of user
alt (validate failed)
"Server" --> "User": password is invalid
else (correct password)
"Server" -> "Server": create jwt token
"Server" -> "User": login succeeded with token and info user
end
end
@enduml