version: '3'

services:
  database:
    image: "mysql:8.0.21"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
  cache:
    image: "redis"
    ports:
      - "6379:6379"
