@startuml addfriend
hide footbox

hide footbox

actor "User A"

"User A" -> "App Server": Sent a POST request (with JWT + username) \nto add a friend
"App Server" -> "Redis Server": Check JWT BlackList
"App Server" -> "App Server": Validate JWT
"App Server" -> "Redis Server": Check username exist
"Redis Server" -> "App Server": True
"App Server" -> "MySql Server": Store in friend list
"App Server" -> "User A": Return result to user A

@enduml