@startuml login
hide footbox
actor User
"User" -> "App Server": login with username and password
activate "App Server"
"App Server" -> "MySql Server": Validate user with hash password
activate "MySql Server"
"MySql Server" --> "App Server": OK
deactivate "MySql Server"
"App Server" --> "App Server": Create JWT
"App Server" -> "Redis Server": Store userId in cache
activate "Redis Server"
"Redis Server" --> "App Server": OK
deactivate "Redis Server"
"App Server" --> "User": Return JWT to User
deactivate "App Server"
"User" -> "App Server": Attach JWT when making request
@enduml